# Generated by Django 4.2.9 on 2024-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.IntegerField()),
                ("user", models.CharField(max_length=100)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
