# Generated by Django 5.0.6 on 2024-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="target_ip",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
